### ISSUE TITLE
Points Value Entered Does Not Update Task String

### ISSUE THREAD

**Issue by GabrielAguilera** [GabrielAguilera/RoomEase#13]

**Comment by GabrielAguilera** [comment]
I'm still getting this issue on master. 😕 
Did I mess up the merge?

**Comment by aboukasm** [comment]
huh no I'm sorry I think I changed it and must have overwritten or stashed the changes :'(((( my b will fix

**Comment by GabrielAguilera** [comment]
np! ✈️

**Comment by aboukasm** [comment]
Ok! This should be fixed now on the bugFixes branch. I will attempt the merge right now
