### ISSUE TITLE
Congratulatory String Gone

### ISSUE THREAD

**Issue by GabrielAguilera** [GabrielAguilera/RoomEase#17]
Probably broke during a merge but not sure which. :/ 

![screen shot 2016-04-05 at 4 28 55 pm](https://cloud.githubusercontent.com/assets/2416867/14297159/83c31570-fb4b-11e5-9c50-2510cc54154f.png)

**Comment by aboukasm** [comment]
I think this is convoluted/bad design anyways. I'm down to close this issue unless we go talk to the UI dude and he says we should have it.
