### ISSUE TITLE
Chat Option Only Appears If Messenger Installed

### ISSUE THREAD

**Issue by GabrielAguilera** [GabrielAguilera/RoomEase#3]

**Comment by aboukasm** [comment]
Right now, the chat option is disabled but the logic is still there, it will just need to be reconnected to the Tab View Controller. This feature can be achieved only through code customization in the ChatViewController.

**Comment by GabrielAguilera** [comment]
I've added this functionality by adding a CustomTabBarController subclass that ties a new TabBarItem to the old ChatViewController we had. It's up on the ChatWork branch.  

Here it is on a simulator with messenger not installed:
![simulator screen shot apr 5 2016 5 15 45 am](https://cloud.githubusercontent.com/assets/2416867/14276624/90d5fef2-faed-11e5-9584-b9ca3199a64a.png)

Here it is on my device with messenger installed:
![screen shot 2016-04-05 at 5 19 09 am](https://cloud.githubusercontent.com/assets/2416867/14276741/fa983e40-faed-11e5-96a0-9e240bb5cb96.png)

If you click the TabBarItem, it'll open messenger right away. When you return to RoomEase, you'll see the ChatViewController with the Messenger button like before but clicking it won't open the app, only clicking the TabBarItem will.

If this looks good on your end too, close the issue and I'll merge into master!

**Comment by aboukasm** [comment]
Hellllll yeahhh dude this is sick! I might change the icon back or find a different one that matches the other two but that can be done later
