### ISSUE TITLE
Outdated Roommate List

### ISSUE THREAD

**Issue by GabrielAguilera** [GabrielAguilera/RoomEase#40]
It looks like we're not actually updating the roommate list when it appears.

Example/Steps to Reproduce:
1. Begin with a user that's part of a house.
2. Sign out of the application
3. Delete the user from firebase
4. Sign in to the application
5. Create a new house
6. Your ranking list will still have your old roommates

The list appears to only refresh after killing the app and loading it again.

**Comment by mgild** [comment]
We should pull from firebase whenever the view loads. not store it at all
Mitchell Brian Gildenberg
mgild@umich.edu
248-508-8421

**Comment by GabrielAguilera** [comment]
Done and on master.
